# Generated by Django 5.1 on 2024-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_status', models.BooleanField(default=False)),
                ('user_request', models.IntegerField()),
            ],
        ),
    ]
